version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.backend
    ports:
      - "8001:8001"

  nginx:
    build:
      context: .
      additional_contexts:
        connectf_react: ../connectf_react
      dockerfile: ./dockerfiles/Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend